version: 2.1

jobs:
  build-with-clang:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y clang cmake build-essential

      - run:
          name: Build with Clang
          command: |
            clang --version
            mkdir build
            cd build
            cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
            cmake --build .

      - run:
          name: Run Tests
          command: |
            cd build
            ctest --output-on-failure

workflows:
  build-workflow:
    jobs:
      - build-with-clang
